# Generated by Django 4.2.30 on 2026-07-15 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(
                        editable=False,
                        help_text="Human-readable appointment number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Client-provided key to prevent duplicate bookings",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("start_datetime", models.DateTimeField(db_index=True)),
                ("end_datetime", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(help_text="Actual appointment duration"),
                ),
                (
                    "reschedule_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this appointment has been rescheduled"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("reason_for_visit", models.TextField(blank=True)),
                ("doctor_notes", models.TextField(blank=True, help_text="Private notes by doctor")),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "cancellation_allowed_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Latest time patient can cancel without penalty",
                        null=True,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("CONFIRMED", "Confirmed"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("NO_SHOW", "No Show"),
                            ("UPDATED", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "previous_values",
                    models.JSONField(
                        blank=True, help_text="JSON snapshot of previous values", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="JSON snapshot of new values", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "db_table": "appointment_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Whether this slot is available for booking"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "appointment_slots",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="RescheduleRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("requested_start_datetime", models.DateTimeField()),
                ("requested_end_datetime", models.DateTimeField()),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "new_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reschedule_source",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "original_appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedule_requests",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "reschedule_requests",
                "ordering": ["-requested_at"],
            },
        ),
    ]
