# Generated by Django 4.2.30 on 2026-07-15 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reschedulerequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_reschedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reschedulerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reschedule_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reserved_slot",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_slots",
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointmenthistory",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmenthistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="previous_appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to original appointment if this is a reschedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_appointments",
                to="appointments.appointment",
            ),
        ),
        migrations.AddIndex(
            model_name="reschedulerequest",
            index=models.Index(
                fields=["original_appointment", "status"], name="reschedule__origina_e453c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reschedulerequest",
            index=models.Index(
                fields=["status", "-requested_at"], name="reschedule__status_4a73e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["doctor", "start_datetime", "is_available"],
                name="appointment_doctor__0d28de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["is_available", "start_datetime"], name="appointment_is_avai_251505_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentslot",
            constraint=models.UniqueConstraint(
                fields=("doctor", "start_datetime"), name="unique_doctor_slot"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmenthistory",
            index=models.Index(
                fields=["appointment", "-changed_at"], name="appointment_appoint_561540_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmenthistory",
            index=models.Index(
                fields=["action", "-changed_at"], name="appointment_action_f65676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "start_datetime"], name="appointment_patient_92fbd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "start_datetime"], name="appointment_doctor__57b194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "start_datetime"], name="appointment_status_9da63e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["idempotency_key"], name="appointment_idempot_6f18e5_idx"),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["SCHEDULED", "CONFIRMED", "IN_PROGRESS"])),
                fields=("doctor", "start_datetime"),
                name="unique_doctor_timeslot",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                check=models.Q(("end_datetime__gt", models.F("start_datetime"))),
                name="end_after_start",
            ),
        ),
    ]
