# Generated by Django 4.2.30 on 2026-07-13 07:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("specialization", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "consultation_duration",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Consultation duration in minutes",
                        validators=[django.core.validators.MinValueValidator(15)],
                    ),
                ),
                (
                    "max_advance_booking_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Maximum days in advance patients can book"
                    ),
                ),
                (
                    "is_accepting_appointments",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the doctor is currently accepting new appointments",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "doctors",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorUnavailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("VACATION", "Vacation"),
                            ("SICK_LEAVE", "Sick Leave"),
                            ("EMERGENCY", "Emergency"),
                            ("CONFERENCE", "Conference"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "affects_existing_appointments",
                    models.BooleanField(
                        default=False,
                        help_text="If True, existing appointments in this period will be flagged for rescheduling",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_unavailability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailability",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_unavailability",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="DoctorWorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "effective_from",
                    models.DateField(help_text="Date when this schedule becomes effective"),
                ),
                (
                    "effective_until",
                    models.DateField(
                        blank=True,
                        help_text="Date when this schedule ends (null = indefinite)",
                        null=True,
                    ),
                ),
                ("break_start_time", models.TimeField(blank=True, null=True)),
                ("break_end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_working_hours",
                "ordering": ["weekday", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "effective_from", "effective_until"],
                        name="doctor_work_doctor__c1effa_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="doctorworkinghours",
            constraint=models.UniqueConstraint(
                fields=("doctor", "weekday", "start_time", "effective_from"),
                name="unique_doctor_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorworkinghours",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gt", models.F("start_time"))),
                name="end_time_after_start_time",
            ),
        ),
        migrations.AddIndex(
            model_name="doctorunavailability",
            index=models.Index(
                fields=["doctor", "start_datetime", "end_datetime"],
                name="doctor_unav_doctor__4f6c0a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorunavailability",
            constraint=models.CheckConstraint(
                check=models.Q(("end_datetime__gt", models.F("start_datetime"))),
                name="unavailability_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["last_name", "first_name"], name="doctors_last_na_55ce7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["specialization"], name="doctors_special_6661e0_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["status", "is_accepting_appointments"], name="doctors_status_c2eb2a_idx"
            ),
        ),
    ]
