# Generated by Django 4.2.30 on 2026-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        # Rename the model from DoctorWorkingHours to DoctorWorkSchedule
        migrations.RenameModel(
            old_name="DoctorWorkingHours",
            new_name="DoctorWorkSchedule",
        ),
        # Rename the database table
        migrations.AlterModelTable(
            name="doctorworkschedule",
            table="doctor_work_schedule",
        ),
        # Update the related_name for the doctor ForeignKey
        migrations.AlterField(
            model_name="doctorworkschedule",
            name="doctor",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="work_schedule",
                to="doctors.doctor",
            ),
        ),
    ]
