# Generated by Django 4.2.30 on 2026-07-13 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorworkschedule_delete_doctorworkinghours_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='doctorworkschedule',
            new_name='doctor_work_doctor__07f141_idx',
            old_name='doctor_work_doctor__c1effa_idx',
        ),
        migrations.AlterField(
            model_name='doctorworkschedule',
            name='break_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctorworkschedule',
            name='break_start_time',
            field=models.TimeField(),
        ),
        migrations.AddConstraint(
            model_name='doctorworkschedule',
            constraint=models.CheckConstraint(check=models.Q(('start_time__gte', datetime.time(6, 0))), name='start_time_within_clinic_hours'),
        ),
        migrations.AddConstraint(
            model_name='doctorworkschedule',
            constraint=models.CheckConstraint(check=models.Q(('end_time__lte', datetime.time(22, 0))), name='end_time_within_clinic_hours'),
        ),
    ]
